-- ═══ BORRADO MASIVO DE CLIENTES FICTICIOS (300) ═══
-- Match exacto por (nombre, direccion). Borra cascade pedidos/boletas/mov_cuenta.
-- Ejecutar TODO en una sola corrida en Supabase SQL Editor.

begin;

create temp table _to_delete (nombre text, direccion text);

insert into _to_delete (nombre, direccion) values
('Adrián', 'San Jeronimo 1377'),
('Adrian EL OMBU 2', 'Ruta c 45 Camiared'),
('Agustina - El Colibri', 'malvinas argentinas 1504'),
('Agustina Kiosco AyS', 'Brasil esquina Lorusso'),
('Alan El Ninja', NULL),
('Aldana', NULL),
('Alejandra - El Tili', 'reconquita 735'),
('Alejandra - Forrajeria Los Nietos', 'ruta S 495 esq las golondrinas'),
('Alejandra - Sangucheria Lurdes', 'Ruta 5 km32.5'),
('Alejandra Maxikiosco', 'Chile 1305'),
('Almacén 4 Hermanos', 'Lavalle 1338'),
('Almacén Rafit', 'Aguirre Camara 1434'),
('Almacen Susi - Valle De Anisacate', NULL),
('Altamirano', 'Gamond 776'),
('Ana Ramos - Kiosco', 'calle 7 entre 10 y 12'),
('Anabella - Despensa Ana', 'los benteveo 215'),
('Analia - Verduleria El Poroto', 'marian moreno.esq reinaldo luppi'),
('Andrea - La Buena Onda', 'nuñez 934'),
('Andrea Valles- Frente A La Fruta', 'Butori esq. Esqui'),
('AndrusEdu', 'americo aguilera 405 casa 2 entre uruguay y bolivia'),
('Angie Castro', 'calle 5 esq 10 santa ana'),
('Arguello Agustina', 'santa maria 1491'),
('Arias María Elena', NULL),
('Ariel Martinez', '24 de September 1247'),
('Ariel Y Monica', 'antun paralelo a Rocío'),
('Ávila Maira - Los 3 Hermanos', 'Fernando Peña 1890'),
('Axel - Limpi-Os', 'Velez Sarsfield 17'),
('Ayelen - B° Pque. Virrey', 'Gamond 1780 (Entre Aguilera y Camara)'),
('Beatriz Ramos', 'Molinari 2024'),
('Belén', 'Julio Antun 825'),
('Berta Barrionuevo', 'poquillines 384'),
('Bibiana Kioskoti', NULL),
('Blanca - Art Limp Casa Blanca', 'consejal alonzo 306'),
('Brenda - Panadería La Florida', NULL),
('Brian Abeldaño', 'Avanzi esq. calle 12'),
('Buena Esperanza', 'bolivia esq. genova'),
('Camping La Playa', 'Ruta 5 y puente anisacate'),
('Candela Kiosco Vizcacha', 'J Anton 825'),
('Carballo Claudia', 'Ricardo balvin e intendente peralta'),
('Carlitos', 'fortunata gonzalez 1856'),
('Carlos Heredia - Mercadito Brochero', 'consejal alonzo 1085'),
('Carmen', NULL),
('Catalina La Pata Loca', 'Irigoyen 1422'),
('Ceci', 'Santa Ana'),
('Ceci - Polleria Pancho', 'calle 14 entre brochero y 7'),
('Cecilia - Maxi Kiosco Monster', 'Av. Libertador (Edificio Betania)'),
('Celeste', NULL),
('Chiringuito', 'ricardo valbin 2066'),
('Claris - Despensa La Esquina', '24 de septiembre esq 3 de febrero'),
('Claudia', 'Americo Aguilera 930'),
('Claudia - Despensa Claudia', 'manzana 25 lote 29 - la marianita'),
('Claudia Kiosco Teo', 'Fernando peña esq A aguilera'),
('Claudia Rosales', 'aguirre camara esq gamond'),
('Claudio', 'Cuyo 539'),
('Coco - Cocomel', 'colectora esq hipolito irygoyen'),
('Cocomel', 'villa del prado'),
('Cristian - Camino La Bolsa', NULL),
('Cynthia manzano', 'calle 7 entre 10 y 12'),
('Daniel Y Ceci - La Huerta', NULL),
('Daniela', 'Dalinger 123'),
('Daniela Girardi', 'calle 8 esq 11'),
('Daniela Kiosko Val-Fran', 'Rossi esq concejal iglesia'),
('Dante Ravera - DR CARNES', NULL),
('Dayana / Productos De Campo', NULL),
('Debora', 'los runduner 554'),
('Delfina - La Despensa', 'calle crucero s/n'),
('Deli - Kiosco Carlitos', 'zorzales 131'),
('Despensa Ana', NULL),
('Despensa Bety', 'Ricardo Balbin 925'),
('Despensa Del Alto', 'zenon britos esq antonio perez'),
('Despensa El Toni', 'Prudencio Bustos 1188'),
('Despensa Gaby - Virrey', 'Ricardo Balbin 1251'),
('Despensa Jena Y Emi', 'consejal caglianone 79'),
('Despensa La Nueva Esquina', '24 de Septiembre Esq. Mariano Moreno'),
('Despensa Loli', 'jonatan brasil 1772'),
('Despensa Lucia', 'Piquillines esq Lo talas'),
('Despensa MANOLITO', NULL),
('Despensa MANOLITO', NULL),
('Despensa Mansilla', 'mansilla 258'),
('Despensa Marttemi', NULL),
('Despensa Matías', 'Suipacha 1430'),
('Despensa Mis Soles', 'molinari 1395'),
('Despensa Noe', 'Fragueiro 13'),
('Despensa Renzo', 'llorens esq. paraguay'),
('Despensa Susy', 'Ecuador 1909'),
('Despensa Vaquita - Jorgelina', 'Paraguay 1469'),
('Diego - Despensa Boca', 'los flamencos 255'),
('Diego - Despensa Chiche', 'av. argentina esq viamonte'),
('Diego Altamitano', 'paez molina esq san martin'),
('Dulce Aroma', 'aguirre camara 1186'),
('El Nuevo Faro - Caro', NULL),
('El Pirata', 'Mza 55 Lot 21'),
('Eli', 'cervantes 207'),
('Eli - Almacén La Gringa', 'ruta 5 esq av argentina - anisacate'),
('Eliana La Esquina', 'Lucas V cordoba 914'),
('Elizabeth - El Rinconcito De Potrero', 'ruta S495 - manzana 71 lote 6 A'),
('Emanuel Vilma - Progreso Esq Patria', NULL),
('Estela', 'Brasil 1819'),
('Fabio', NULL),
('Fanny - Despensa Fanny', 'los zorzales 165'),
('Félix', 'Lozada 762'),
('Fernando', NULL),
('Fernando  Ramirez', 'prudencio bustos y ema ceballos'),
('Fernando Secco - Seccolimp', 'calle 12 entre 9 y 11'),
('Flavia', NULL),
('Flavia DON TETE', 'Nahal esq B Roldan'),
('Flor Calle Brasil', NULL),
('Florencia - Punto Cero', 'arzobispo castellano 251'),
('Franco - Despensa Ochoa', 'catamarca 993'),
('Franco - Maxikiosco Monster', 'Urquiza 278'),
('Franco Torrez - Verduleria Genesis', 'olga diaz 50'),
('Gabriela', NULL),
('Gabriela - Kiosco Athos', 'butori - 219'),
('Gabriela Virrey', 'Av. Virrey 500'),
('Gabriela Y Walter', 'Barbeito 286'),
('Gaby - Panadería', NULL),
('Gerardo - Despensa GC', 'rioja este 202'),
('Gise', 'V'),
('Gise Eggers', 'J. P. Molina 387'),
('Gisel Astrada', 'ema ceballos 431 (08:00 a 17hs)'),
('Gisela - La Rosada', NULL),
('Gisela - La Rosada', NULL),
('Gisele', 'godoy nuñez 358'),
('Graciana', NULL),
('Graciela Heredia', 'santa maria 1449'),
('Guada', 'consejal iglesias 122'),
('Guillermo', 'Roberto Saieg 1316'),
('Gustavo Farfan', 'las gaviotas 239'),
('Hector', NULL),
('Hector Sabattini', 'juares celman esq. justo paez molina'),
('Hugo - Belgrano Y Salta', NULL),
('Hugo Distri', NULL),
('Isabel - Despensa Isa', 'calle 8 entre 11 y 13 - santa ana'),
('Iva Quintero', NULL),
('Jaimee', NULL),
('Jesica', NULL),
('Jesica - Despensa Zulma', 'lucia irusta 500'),
('Jesica Velarde - Despensa EyL', 'calla 20 451 - entre brochero y calle 7'),
('Joaquín - Kiosco De La 24', '24 de September 0290'),
('José Kiosco La Esquina', 'Avanzi esquina calle 3'),
('Juan Carlos Fernández', 'Av. de mayo 279'),
('Juan Italia', 'italia esquina chile a mano izquierda'),
('Juancho Jorge', 'victor fernandez sn'),
('Juani', NULL),
('Juliana - La Buena Onda', NULL),
('Julieta - Fiambres Del Prado', 'reinaldo luppi 1050'),
('Julio Cesar Romero', 'M. Luque'),
('Karina - Costa Azul', 'camino costa azul mzna 2 lote 2'),
('Karina Ferreyra', NULL),
('Kassandra P. Papel O Tijera', 'Av Libertador 945'),
('Kiosco Chela', 'Ruta 5 fte Colonia de Anisacate'),
('Kiosco Claudio', 'España 480'),
('Kiosco Estilo', 'Mirta'),
('Kiosco Gsc', 'mza 55 lot 21'),
('Kiosco Mabel', 'C publica 2 casa 65'),
('Kiosco Mirta', 'Carcano 142'),
('Kiosco Sandrito 2', 'Ruta 5 ( pasando la curva de la iglesia )'),
('Kiosco Te', 'bahia blanca esq. constantini'),
('Kiosco Vanessa', 'Barbeito 221'),
('Kiosko Tini', NULL),
('La Despensa "De Bauti"', 'Los Chañares 1881'),
('Laura Miranda', 'barcelona 212'),
('Lautaro - Fresh', 'av leandro alem 300'),
('Leila Farias - Despensa J y B', 'salta esq hnos maure'),
('Leo', NULL),
('Leoso', 'san martin 340'),
('Lesli - Verduleria El Piray', 'manzana 55 lote 21 - los talas'),
('Liliana - Maxikiosco La Rivera', NULL),
('Liliana Zalazar', 'e velazques 443'),
('Lo De Deivid', 'españa 138'),
('Lore - Kiosco Lauti', 'gaviotas esq canarios'),
('Los Rusitos', 'Consejal Alonso 1280'),
('Los Tres Pinos - Liliana', 'ruta S495'),
('Lucas', NULL),
('Lucia - Despensa Lu', 'aldo monjes 2200'),
('Luli', 'Los Pelicanos'),
('Luli', 'Los Pelicanos'),
('Luz Zigaran - Minimercado Prishano', 'Rcta Montenegro'),
('Macarena Kiosco Delfina', 'Gabino ezeiza 545'),
('Marcela', 'ema ceballos 431'),
('Marcelo - Perrito', 'reinaldo.luppi esq rivadavia'),
('Marcelo - Va Como Loco', NULL),
('Marcos - Mr Limpio', 'alfoncin 63 - al lado de tarjeta naranja'),
('Maria - Maria Y Elias', 'calle 9 entre 8 y 10'),
('Maria José Lo De Terna', 'Lucas v Cordoba 1068'),
('María Laura', NULL),
('María Moyano Chañares', 'los chañares 1735'),
('María Sol - Parada 34', 'ruta 5 km 34'),
('Mariana', 'los flamencos esq pelicanos'),
('Mariana - Lo De Pichon', NULL),
('Mariana Calle San Juan', 'san juan 368'),
('Mariana González', 'volta 1273'),
('Marianela', 'los zorzalez 257'),
('Mariela Altamirano', 'peru.y.cuba 1191'),
('Mariela Kiosco Julian', 'lucas v cordoba 811'),
('Marina - Despensa Díaz', 'B. de Galvez 381'),
('Marjes Fortunata González 1651', NULL),
('Matías Giordano - Maxikiosco 70/30', 'urquiza 268 ( ex monster)'),
('Maxikiosco 24/7', 'La Lechuza 292'),
('Maxikiosco Agustin', 'chubut 540'),
('Maxikiosco Anisacate', NULL),
('Maxikiosco Yimbo', 'frente plaza solares'),
('Mayra - Mi Sueño', 'Int. Llorens y Matheu'),
('Meli V. Prado', NULL),
('Mercedes - Despensa Merci', 'rioja 351'),
('Mercedes Aspitia', NULL),
('Mica', 'distri los pinos'),
('Mili', 'zabala ortiz 1643'),
('Miner Boy''S', 'carcna s/n (frente esc)'),
('Minimercado Candela', 'Santillan esq. Lucio V Rossi'),
('Minimercado Nacho', 'llorens esq. a. aguirre'),
('Minimercado Valerio', 'Perazzo 1550'),
('Miriam', 'Calle 10 esq Valdez'),
('Miriam - Fac''s', 'Llorens 380/382'),
('Mirian - Heladeria Via Bana', 'calle 5 entre 8 y 10'),
('Mirta Murua', 'Carcanos 142'),
('Mónica Ferrer', 'ruta 5 km 37.5 ( ex don emilio)'),
('Moreno Natalia Charito', 'alem 250'),
('Nadia _ Kiosco Tatino', 'peron 351'),
('Nahuel Kiosco Nagus', 'Irigoyen esq Anton'),
('Name', 'Email'),
('Nano Minimercado - Lucio', 'italia esq. uruguay'),
('Naty - Polleria Don Emilio', 'ruta 5 km. 37,5'),
('Nelida - La Serranita', 'entrada serranita'),
('Nena', 'Montamat 771'),
('Noe - Mamina Rubi', 'celestina aguero 55'),
('Noe Alvear', 'alvear 161'),
('Noelia', 'carlos besso 840'),
('Noelia  F. Peña', 'Fernando Peña 1850'),
('Noelia - Despensa Candela', 'av brochero 620'),
('Noelia - Despensa La Biela', 'catamarca 698'),
('Noelia - Virrey', 'Fernando Peña 1349'),
('Noelia La Quinta', 'paraguay 1278'),
('Norma - Las Nietas', 'calle 6 entre 11 y 13'),
('Pablo Prodan - 212 Despensa', 'cervantes 207 - ex silvia olmos.'),
('Pame', NULL),
('Panadería La Loma', 'Manuel Solares'),
('Panadería Los Mellis', NULL),
('Paola López', 'godoy nuñez 344'),
('Para MATEO NO REPARTIR', NULL),
('Pato La Donosa', NULL),
('Paula Kiosco Capybara', 'Barbeito 210'),
('Peque - Panadería Alma', 'butoru 226'),
('Polleria Don Luis', 'Ruta 5 Km 33'),
('Punto Cero', 'arzobispo catellano 251'),
('Punto Shop', 'Halcon 377'),
('Ramiro - Almacen24/7', 'Julio Antun 530'),
('Reinaldo Olmedo', 'los llantenes 210'),
('Rober', 'canarios 100'),
('Roberto - Desp La Cleta', 'mariano moreno 571'),
('Roberto Caminos', 'ruta s495 barrio parque - kiosco naranja'),
('Rocio', NULL),
('Rocío', NULL),
('Rocio - La Esquina De Rojo', 'calle 7 esq calle 2.santa ana'),
('Roque Aguirre', 'P. Bustos esquina Carignani'),
('Rosa - Los 5 Hermanos', 'reinaldo lupis s.n'),
('Rosa - Mercemaria', 'azucena barrera 1425'),
('Rosa-Despensa Charli', 'Uruguay 1741'),
('Roxana', 'Margarita Funes 232'),
('Rubén', 'Av. de mayo 490'),
('Sandra', 'Santa Ana'),
('Sandra Bilche - Despensa Santa Rita', 'calle 9 entre 8 y 10'),
('Sandra Mafalda', 'agustin aguirre y alvear'),
('Sergio', 'Julio Antun 1456'),
('Sergio - ( Ex Silvia Olmos)', NULL),
('Sergio AUTOSERVICIO MAX', 'B.roldan Esq Lucio Rossi'),
('Silvana Kiosco Virgen Del Valle', 'Ema ceballos esq P Bustos'),
('Silvia', NULL),
('Silvia - Babas', '24 de September 1678'),
('Silvia Fernández', 'Fernando Peña 974'),
('Silvia Olmos', 'cervantes 207'),
('Silvia Valdovino - Maxikiosco Irma', NULL),
('Soledad- kiosco Mari', 'Olmos 1471'),
('Sonia', 'Montamat 1271'),
('Sonia Arguello', 'los flamencos 491'),
('Stella', NULL),
('Susi', 'Brasil 1123'),
('Tania Tello - Despensa Malilu', 'el valle 256 - villa montenegro'),
('Tere - TB ( Benja)', 'reinaldo luppi 1300'),
('Tres Hermanos', 'raul alfonsin 1190 esq cuba'),
('Trinidad - Kiosco Carlita', 'butori 319'),
('Trinidad - Kiosco Neon', 'Montamat 850'),
('Tucu Y El Gringo', 'Pelicanos esq. venteveo'),
('Tucumano', NULL),
('Vale Fabito', 'fabian'),
('Valeria', 'falucho 907'),
('Vane', NULL),
('Vaquel Jesica Melisa - Despensa Mis Angeles', NULL),
('Vega Asucena Elena', NULL),
('Verónica - Maxi Carne (Fabio)', 'hipolito irigoyen 1500'),
('Verónica Minimercado Virrey', 'Bahia Blanca esq Constantini'),
('Viviana - Verde Manzana', 'calle 3 entre 6 y 8'),
('Viviana Domínguez', 'Esmeralda 438'),
('Yamila - La Mendocina', 'rio del medio s/n'),
('Yanina - JoYa Kiosco', 'Irigoyen 1680'),
('Yazmin - Pollería Ruta 5', NULL),
('Yohana', NULL),
('Yohana - Lo De Bruno', 'manznaa 16 lote 11 Valle alegre'),
('Yohana - Tío Pelado', 'Av. Libertador 820'),
('Zuperkiosco Kasi To - Flavia', NULL);

-- IDs de clientes a borrar
create temp table _target_ids as
  select c.id
    from public.clientes c
    join _to_delete t
      on btrim(c.nombre) = btrim(t.nombre)
     and coalesce(btrim(c.direccion),'') = coalesce(btrim(t.direccion),'');

-- conteos previos
do $$
declare
  n_target int; n_no_match int; n_pedidos int; n_bol int; n_mov int;
begin
  select count(*) into n_target from _target_ids;
  select count(*) into n_no_match
    from _to_delete t
    where not exists (
      select 1 from public.clientes c
       where btrim(c.nombre) = btrim(t.nombre)
         and coalesce(btrim(c.direccion),'') = coalesce(btrim(t.direccion),'')
    );
  select count(*) into n_pedidos from public.pedidos where cliente_id in (select id from _target_ids);
  select count(*) into n_bol from public.boletas where pedido_id in (select id from public.pedidos where cliente_id in (select id from _target_ids));
  select count(*) into n_mov from public.mov_cuenta where cliente_id in (select id from _target_ids);
  raise notice 'Clientes a borrar: %', n_target;
  raise notice 'No encontrados en DB: %', n_no_match;
  raise notice 'Pedidos asociados (se borran): %', n_pedidos;
  raise notice 'Boletas asociadas (se borran): %', n_bol;
  raise notice 'Mov_cuenta asociados (se borran): %', n_mov;
end $$;

-- Borrar dependientes en orden
delete from public.mov_cuenta where cliente_id in (select id from _target_ids);
delete from public.boletas    where pedido_id in (select id from public.pedidos where cliente_id in (select id from _target_ids));
-- pedido_items cae por CASCADE al borrar pedidos
delete from public.pedidos    where cliente_id in (select id from _target_ids);
-- visitas_clientes cae por CASCADE al borrar clientes
delete from public.clientes   where id in (select id from _target_ids);

-- ⚠️ Revisá los mensajes "NOTICE" arriba.
-- Si todo OK → ejecutá: commit;
-- Si algo no cuadra → ejecutá: rollback;
-- (esta query ya hizo COMMIT automático al final)

commit;
